### HELLO WORLD, I AM PEDA ALPHA...

<a target="_blank" align="center">
  <img align="right" top="500" height="300" width="400" alt="GIF" src="https://media.giphy.com/media/SWoSkN6DxTszqIKEqv/giphy.gif">
</a>


<!--
**PEDA-ALPHA1/PEDA-ALPHA1** is a ✨ _special_ ✨ repository because its `README.md` (this file) appears on your GitHub profile.

Here are some ideas to get you started:

- 🔭 I’m currently working on ...
- 🌱 I’m currently learning ...
- 👯 I’m looking to collaborate on ...
- 🤔 I’m looking for help with ...
- 💬 Ask me about ...
- 📫 How to reach me: ...
- 😄 Pronouns: ...
- ⚡ Fun fact: ...
-->

### Programming Languages....

<p align="left">
<img width="5%" style="padding:5px" src="https://img.icons8.com/color/48/000000/c-programming.png"/>
<img width="5%" style="padding:5px" src="https://img.icons8.com/color/144/000000/python.png"/>
<img width="5%" style="padding:5px" src="https://img.icons8.com/color/144/000000/javascript.png"/>
</p>
